jwtproxy:
  signer:
    listenaddr: :8080
    # CA used to forge certificates used by
    # the proxy's MITM mechanism.
    cakeyfile: ca.key
    cacrtfile: ca.crt
  verifier:
    listenaddr: :8082
    upstream: http://127.0.0.1:8888/
    # Key pair used to terminate TLS.
    keyfile: localhost.key
    crtfile: localhost.crt
